name: CMake

on:
  push:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt install libspdlog-dev libvncserver-dev libfmt-dev build-essential clang cmake
    
    - name: Build Boost
      run: |
        wget https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.tar.gz
        tar –xvzf boost_1_77_0.tar.gz -C boost
        cd boost
        ./bootstrap.sh
        sudo ./b2 install
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build collab-vm-server
      run: cmake --build && ls && ls build
